AWSTemplateFormatVersion : '2010-09-09'
Transform:
  - AWS::Serverless-2016-10-31
  
Parameters:
  Project: 
    Type: String

Description: my template
Resources:
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: lambdarol-common
      ManagedPolicyArns: 
        - 'arn:aws:iam::aws:policy/AmazonDynamoDBFullAccess'
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Path: "/"
      Policies:
      - PolicyName: my-lambda-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - dynamodb:BatchGetItem
            - dynamodb:GetItem
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWriteItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
            Resource: arn:aws:dynamodb:*:*:table/pets
  
  MyAPI:
    Type: AWS::Serverless::Api
    Properties:
      Name: my-api-Mascotws
      StageName: prod
      DefinitionBody:
        Fn::Transform:
          Name: AWS::Include
          Parameters:
            Location: swagger.yaml
  
  GetData:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: GetData
      Runtime: python3.6
      CodeUri: ./build
      Handler: lambda1.handler
      Timeout: 30
      MemorySize: 500
      Role: !GetAtt MyLambdaRole.Arn
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: /pets
            Method: POST
            
  Table:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: Table
      Runtime: python3.6
      CodeUri: ./build
      Handler: lambda2.handler
      Timeout: 30
      MemorySize: 500
      Role: !GetAtt MyLambdaRole.Arn
      Events:
        GetUsers:
          Type: Api
          Properties:
            RestApiId: !Ref MyAPI
            Path: /Table
            Method: GET
  
Outputs: 
  RoleARN:
    Value: !GetAtt MyLambdaRole.Arn 