AWSTemplateFormatVersion: '2010-09-09'
Transform:
- AWS::Serverless-2016-10-31
Parameters:
  Project:
    Type: String
Description: miaw bucked excel images
Resources:
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: miaw-migration-lectura-excel-imagenes-1
      
 