AWSTemplateFormatVersion: '2010-09-09'

Transform:
  - AWS::Serverless-2016-10-31

Description: miaw bucked excel images
Resources:
  
  MyLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: migration-role-lambda-migration
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
        - Effect: Allow
          Principal:
            Service:
            - lambda.amazonaws.com
          Action:
          - sts:AssumeRole
      Policies:
      - PolicyName: my-lambda-policy
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
          - Effect: Allow
            Action:
            - logs:CreateLogGroup
            - logs:CreateLogStream
            - logs:PutLogEvents
            Resource: arn:aws:logs:*:*:*
          - Effect: Allow
            Action:
            - s3:PutObject
            - s3:PutObjectAcl
            - s3:GetObject
            - s3:GetObjectAcl
            - s3:DeleteObject
            Resource: arn:aws:s3:::*/*
          - Effect: Allow
            Action:
            - dynamodb:BatchGet
            - dynamodb:DescribeStream
            - dynamodb:DescribeTable
            - dynamodb:Get*
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:BatchWrite*
            - dynamodb:CreateTable
            - dynamodb:Delete*
            - dynamodb:Update*
            - dynamodb:PutItem
            Resource: arn:aws:dynamodb:*:*:table/*
            
  MyLambdaMiawMigration:
    Type: AWS::Serverless::Function
    Properties:
       FunctionName: lambda-migration
       Runtime: python3.6
       CodeUri: ./build
       Handler: lambda-migration.lambda_handler
       Role: !GetAtt MyLambdaRole.Arn
       Events:
        S3Event:
          Type: S3
          Properties:
            Bucket: miaw-migration-lectura-excel-imagenes-1
            Events: s3:ObjectCreated:*
       
  MyBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: miaw-migration-lectura-excel-imagenes-1
      
 