AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB for Animal Adoption
Resources:
  MyDatabase:
    Type: AWS::DynamoDB::Table
    Properties: 
      TableName: "animal-adoption"
      KeySchema: 
        - AttributeName: PK
          KeyType: HASH
        - AttributeName: SK
          KeyType: RANGE
      AttributeDefinitions: 
        - AttributeName: PK
          AttributeType: S
        - AttributeName: SK
          AttributeType: S
      ProvisionedThroughput: 
        ReadCapacityUnits: 5
        WriteCapacityUnits: 5
    
    